/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  rapidPlanSidebar: [{ type: 'autogenerated', dirName: 'rapid-plan' }],
  rapidPlanOnlineSidebar: [{ type: 'autogenerated', dirName: 'rapid-plan-online' }],
  rapidPathSidebar: [{ type: 'autogenerated', dirName: 'rapid-path' }],
  rapidPathOnlineSidebar: [
    { type: 'autogenerated', dirName: 'rapid-path-online' },
  ],
  accountManagementSidebar: [
    { type: 'autogenerated', dirName: 'account-management' },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
