/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  rapidPlanSidebar: [{ type: 'autogenerated', dirName: 'rapidplan' }],
  rapidPlanOnlineSidebar: [{ type: 'autogenerated', dirName: 'rapidplan-online' }],
  rapidPathSidebar: [
    'rapidpath/Welcome',
    {
      type: 'category',
      label: 'Swept Path Analysis',
      link: { type: 'generated-index' },
      items: [
        'rapidpath/swept-path-analysis/What-is-Swept-Path-Analysis',
        'rapidpath/swept-path-analysis/Definitions',
        'rapidpath/swept-path-analysis/Preparing-Swept-Path-Analysis',
        'rapidpath/swept-path-analysis/swept-path-analysis-properties',
        'rapidpath/swept-path-analysis/using-vehicle-library',
        'rapidpath/swept-path-analysis/animating-vehicle-movement',
        'rapidpath/swept-path-analysis/using-swept-path-annotation-items',
      ],
    },
    'rapidpath/signs-in-rapidpath',
    {
      type: 'category',
      label: 'FAQs',
      link: { type: 'generated-index' },
      items: [
        'rapidpath/faqs/we-have-rapidplan-how-can-i-access-rapidpath',
        'rapidpath/faqs/what-licensing-options-are-available-for-rapidpath',
        'rapidpath/faqs/what-are-rapidpaths-minimum-system-requirements',
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      link: { type: 'generated-index' },
      items: [
        'rapidpath/release-notes/official',
        'rapidpath/release-notes/hotfix',
        'rapidpath/release-notes/weekly',
      ],
    },
    {
      type: 'category',
      label: '↗ Shared RapidPlan Docs',
      link: { type: 'doc', id: 'rapidpath/shared-rapidplan-docs' },
      collapsed: false,
      items: [
        { type: 'link', label: '↗ Home Screen and Starting a Plan', href: '/category/the-home-screen--starting-a-plan' },
        { type: 'link', label: '↗ Workspace and Palettes Overview', href: '/category/workspace--palettes-overview' },
        { type: 'link', label: '↗ Toolbar', href: '/category/the-toolbar' },
        { type: 'link', label: '↗ Canvas Area', href: '/category/the-canvas-area' },
        { type: 'link', label: '↗ Tools Palette', href: '/category/the-tools-palette' },
        { type: 'link', label: '↗ Object Properties and Transformations', href: '/category/object-properties--transformations' },
        { type: 'link', label: '↗ Using Layers', href: '/category/using-layers' },
        { type: 'link', label: '↗ Scratchpad', href: '/category/the-scratchpad' },
        { type: 'link', label: '↗ Integrated Mapping', href: '/category/integrated-mapping' },
        { type: 'link', label: '↗ Using the Invarion Cloud', href: '/category/using-the-invarion-cloud' },
        { type: 'link', label: '↗ Exporting Plans', href: '/category/exporting-plans' },
      ],
    },
  ],
  rapidPathOnlineSidebar: [
    'rapidpath-online/Welcome',
    {
      type: 'category',
      label: 'Swept Path Analysis',
      link: { type: 'generated-index' },
      items: [
        'rapidpath-online/swept-path-analysis/preparing-swept-path-analysis',
        'rapidpath-online/swept-path-analysis/definitions',
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      link: { type: 'generated-index' },
      items: [
        'rapidpath-online/release-notes/release-notes-rapidpath-online',
      ],
    },
    {
      type: 'category',
      label: '↗ Shared RapidPlan Online Docs',
      link: { type: 'doc', id: 'rapidpath-online/shared-rapidplan-online-docs' },
      collapsed: false,
      items: [
        { type: 'link', label: '↗ Getting Started', href: '/category/getting-started' },
        { type: 'link', label: '↗ The Invarion Cloud', href: '/category/the-invarion-cloud' },
        { type: 'link', label: '↗ RapidPlan Online Workspace', href: '/category/rapidplan-online-workspace' },
        { type: 'link', label: '↗ RapidPlan Online Basics', href: '/category/rapidplan-online-basics' },
        { type: 'link', label: '↗ The Road Tool', href: '/category/the-road-tool-1' },
        { type: 'link', label: '↗ The Marker Tool', href: '/category/the-marker-tool' },
        { type: 'link', label: '↗ Location Based Features', href: '/category/location-based-features' },
        { type: 'link', label: '↗ Printing and Exporting', href: '/category/printing-and-exporting' },
        { type: 'link', label: '↗ Using Mobile Devices', href: '/category/using-mobile-devices' },
      ],
    },
  ],
  accountManagementSidebar: [
    { type: 'autogenerated', dirName: 'account-management' },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
