name: Pull request actions on DevTeamTasks project

on:
  pull_request:
    types: [opened, closed, review_requested, review_request_removed]
    
  pull_request_review:
    types: [submitted, dismissed]
    
  create:

jobs:
  call_pr_actions:
    name: Call DevTeamTasksRepo/Pull request actions
    uses: Invarion/DevTeamTasksRepo/.github/workflows/pull_request_actions.yml@main
    with:
      action: "${{ github.event_name }}.${{ github.event.action }}"
      sender: ${{ github.event.sender.login }}
      pr_repo: ${{ github.event.repository.full_name }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_url: ${{ github.event.pull_request.html_url }}
      pr_branch: ${{ github.event.pull_request.head.ref }}
      pr_merged: ${{ github.event.pull_request.merged }}      
      pr_body: ${{ github.event.pull_request.body }}
      requested_reviewer: ${{ github.event.requested_reviewer.login }}
      review_user: ${{ github.event.review.user.login }}
      review_state: ${{ github.event.review.state }}
      review_body: ${{ github.event.review.body }}
      branch_ref: ${{ github.event.ref }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ORG_PROJECTS_PAT }}  
